### ISSUE TITLE
pycisTopic.clust_vis.cell_topic_heatmap

### ISSUE THREAD

**Issue by TingTingShao** [aertslab/pycisTopic#129] opened 2024-04-11 09:45 UTC
In API, argument should be changed into `color_dict`.

Thanks,
tingting

**Comment by ghuls** [comment] 2024-04-11 13:11
This was recently fixed in the main branch: https://github.com/aertslab/pycisTopic/commit/bb75dc9ee2ce8997101cfa84c75776c9687ed2da

**Comment by TingTingShao** [comment] 2024-04-12 09:21
Thanks for your reply. I meant here `https://pycistopic.readthedocs.io/en/latest/api.html#pycisTopic.clust_vis.cell_topic_heatmap` the documentary.

Thanks,
tingting

**Closed** 2024-04-17 14:31 UTC

**Comment by tuqiang2014** [comment] 2024-05-31 21:15
When I re-analyzed it, I found:

```
cell_topic_heatmap(
    cistopic_obj,
    variables = ['pycisTopic_leiden_10_0.6'],
    scale = False,
    legend_loc_x = 1.0,
    legend_loc_y = -1.2,
    legend_dist_y = -1,
    figsize = (10, 10)
)
```

The error message is as follows


```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[52], line 1
----> 1 cell_topic_heatmap(
      2     cistopic_obj,
      3     variables = ['pycisTopic_leiden_10_0.6'],
      4     scale = False,
      5     legend_loc_x = 1.0,
      6     legend_loc_y = -1.2,
      7     legend_dist_y = -1,
      8     figsize = (10, 10)
      9 )

File ~/miniforge3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/clust_vis.py:951, in cell_topic_heatmap(cistopic_obj, variables, remove_nan, scale, cluster_topics, color_dictionary, seed, legend_loc_x, legend_loc_y, legend_dist_y, figsize, selected_topics, selected_cells, harmony, save)
    948 var_data = cell_data.loc[:, var].sort_values()
    949 categories = set(var_data)
--> 951 if var not in color_dictionary:
    952     random.seed(seed)
    953     color = [
    954         mcolors.to_rgb("#" + "%06x" % random.randint(0, 0xFFFFFF))
    955         for i in range(len(categories))
    956     ]

TypeError: argument of type 'NoneType' is not iterable
```
Some data information
```
cistopic_obj.cell_data.columns

Index(['nucleosome_signal', 'VSN_leiden_res0.3', 'duplication_ratio',
       'Seurat_leiden_res1.2', 'total_fragments_in_peaks_count',
       'pdf_values_for_tss_enrichment', 'unique_fragments_in_peaks_count',
       'pdf_values_for_duplication_ratio', 'VSN_leiden_res0.9',
       'cisTopic_nr_frag', 'cisTopic_log_nr_frag', 'barcode_rank',
       'unique_fragments_count', 'log10_total_fragments_in_peaks_count',
       'duplication_count', 'Seurat_cell_type', 'VSN_cell_type',
       'VSN_leiden_res1.2', 'log10_unique_fragments_in_peaks_count',
       'total_fragments_count', 'sample_id', 'log10_total_fragments_count',
       'VSN_sample_id', 'tss_enrichment', 'Seurat_leiden_res0.6',
       'cisTopic_nr_acc', 'log10_unique_fragments_count', 'VSN_leiden_res0.6',
       'fraction_of_fragments_in_peaks', 'cisTopic_log_nr_acc',
       'pdf_values_for_fraction_of_fragments_in_peaks', 'barcode',
       'Doublet_scores_fragments', 'Predicted_doublets_fragments',
       'pycisTopic_leiden_10_0.6', 'pycisTopic_leiden_10_1.2',
       'pycisTopic_leiden_10_3'],
      dtype='object')
```

```
cistopic_obj.region_data.columns
Index(['Chromosome', 'Start', 'End', 'Width', 'cisTopic_nr_frag',
       'cisTopic_log_nr_frag', 'cisTopic_nr_acc', 'cisTopic_log_nr_acc'],
      dtype='object')
```

```
cistopic_obj.selected_model.cell_topic.index
Index(['Topic1', 'Topic2', 'Topic3', 'Topic4', 'Topic5', 'Topic6', 'Topic7',
       'Topic8', 'Topic9', 'Topic10', 'Topic11', 'Topic12', 'Topic13',
       'Topic14', 'Topic15', 'Topic16', 'Topic17', 'Topic18', 'Topic19',
       'Topic20', 'Topic21', 'Topic22', 'Topic23', 'Topic24', 'Topic25',
       'Topic26', 'Topic27', 'Topic28', 'Topic29', 'Topic30', 'Topic31',
       'Topic32', 'Topic33', 'Topic34', 'Topic35', 'Topic36', 'Topic37',
       'Topic38', 'Topic39', 'Topic40'],
      dtype='object')



```

**Comment by leahyekim** [comment] 2024-06-03 03:54
I get the exact same error as @tuqiang2014 here as well.

My cistopic_obj looks pretty similar to @tuqiang2014 's.

Does anyone have an idea why we're getting that error? @ghuls

**Comment by JBreunig** [comment] 2024-06-17 18:44
Same error here:
TypeError: argument of type 'NoneType' is not iterable

**Comment by cathynewman** [comment] 2024-07-08 17:57
@tuqiang2014 @leahyekim @JBreunig I am getting the same error. It appears that `color_dictionary` may actually be required now and not optional (or at least including it fixed this error for me), and that it has to include all variable levels and only those variable levels, in the format `my_color_dict = {"variablename":{"level1":"#e36296", "level2":"#color",...}}`

From what I can tell, the TypeError is being generated because there is no `color_dictionary` object for the line `if var not in color_dictionary:` to run. Once I made my own `color_dictionary`, the function worked.

**Comment by JBreunig** [comment] 2024-07-10 05:01
I can confirm that @cathynewman's solution fixes my error and allows the function to work.
